sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php: 7.0

env:
  global:
    - CODE_COVERAGE=false

  matrix:
    - MAGENTO_VERSION=2.0.16
    - MAGENTO_VERSION=2.0.17
    - MAGENTO_VERSION=2.1.9
    - MAGENTO_VERSION=2.1.10
    - MAGENTO_VERSION=2.2.0
    - MAGENTO_VERSION=2.2.1

matrix:
  include:
  # PHP 7.1 would be supported in Magento since Magento 2.2
  # And there wouldn't be support of PHP 7.1 in Magento 2.0 or 2.1
    php: 7.1
    env: MAGENTO_VERSION=2.2.1 CODE_COVERAGE=true

before_script:
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - bash Test/Script/ManageDependencies.sh

script:
  - bash Test/Script/Setup.sh

after_success:
  - bash Test/Script/AfterSuccess.sh

cache:
  directories:
  - $HOME/.composer/cache
