sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.1

env:
  - MAGENTO_VERSION=2.0.8
  - MAGENTO_VERSION=2.0.9

before_script:
  - phpenv config-rm xdebug.ini
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json

script:
  - bash Test/setup.sh

cache:
  directories:
  - $HOME/.composer/cache