sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php:
    - 7.1

env:
  global:
    - CODE_COVERAGE=false

  matrix:
    - MAGENTO_VERSION=2.3.0

matrix:
  include:
  # Magento 2.3 supports only PHP 7.1 and 7.2
    - php: 7.2
      env: MAGENTO_VERSION=2.3.0
    - php: 7.1
      env: MAGENTO_VERSION=2.3.0 CODE_COVERAGE=true

before_script:
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - bash Test/Script/ManageDependencies.sh

script:
  - bash Test/Script/Setup.sh

after_success:
  - bash Test/Script/AfterSuccess.sh

cache:
  directories:
  - $HOME/.composer/cache
