sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php:
  - 7.0

env:
  - MAGENTO_VERSION=2.0.8
  - MAGENTO_VERSION=2.0.9
  - MAGENTO_VERSION=2.0.10
  - MAGENTO_VERSION=2.1.0
  - MAGENTO_VERSION=2.1.1
  - MAGENTO_VERSION=2.1.2

before_script:
  - phpenv config-rm xdebug.ini
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - npm install -g travis-notify-geckoboard

script:
  - bash Test/setup.sh

cache:
  directories:
  - $HOME/.composer/cache

after_script: travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
