sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php:
  - 7.0

env:
  global:
    - CODE_COVERAGE=false

  matrix:
    - MAGENTO_VERSION=2.0.8
    - MAGENTO_VERSION=2.0.9
    - MAGENTO_VERSION=2.0.10
    - MAGENTO_VERSION=2.1.0
    - MAGENTO_VERSION=2.1.1
    - MAGENTO_VERSION=2.1.2
    - MAGENTO_VERSION=2.1.3

matrix:
  include:
    env: MAGENTO_VERSION=2.1.5 CODE_COVERAGE=true

before_script:
  - if [ "$CODE_COVERAGE" = "false" ]; then phpenv config-rm xdebug.ini; fi
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - npm install -g travis-notify-geckoboard

script:
  - bash Test/Script/Setup.sh

after_success:
  - bash Test/Script/AfterSuccess.sh

cache:
  directories:
  - $HOME/.composer/cache

after_script: travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
