language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.1

env:
  - MAGENTO_VERSION=2.0.8
  - MAGENTO_VERSION=2.0.9

before_script:
  - phpenv config-rm xdebug.ini
  - composer global require n98/magerun
  - composer global require colinmollenhour/modman
  - export PATH=$PATH:$HOME/.composer/vendor/bin

script:
  - bash Test/setup.sh

cache:
  directories:
  - $HOME/.composer/cache